import{a as p,S as E,i as d}from"./assets/vendor-527658dd.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const L="42458778-da79c0017118817650d1b611e";async function u(r,n=1,e=15){try{return(await p.get(`https://pixabay.com/api/?key=${L}&q=${r}&page=${n}&per_page=${e}`)).data}catch(s){throw console.error("Error fetching data:",s),s}}const w=document.getElementById("loader"),I=document.getElementById("gallery"),$=new E(".gallery a"),y=document.getElementById("loadMoreBtn");function f(r,n){if(w.style.display="none",r.length===0){d.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}n&&m(),r.forEach(e=>{const s=document.createElement("div");s.classList.add("card"),s.innerHTML=`
            <a href="${e.largeImageURL}" data-lightbox="gallery">
                <img src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
        `,I.appendChild(s)}),$.refresh()}function l(){y.style.display="none"}function m(){y.style.display="block"}function b(){d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const B=document.getElementById("searchForm"),h=document.getElementById("searchInput"),c=document.getElementById("loader"),v=document.getElementById("gallery"),g=document.getElementById("loadMoreBtn");let a=1;B.addEventListener("submit",async function(r){r.preventDefault();const n=h.value.trim();if(n===""){iziToast.error({title:"Error",message:"Please enter a search term"});return}c.style.display="block",v.innerHTML="";try{const e=await u(n,a);f(e.hits,a===1),e.hits.length===0?l():(m(),a++)}catch(e){c.style.display="none",console.error("Error fetching data:",e),iziToast.error({title:"Error",message:"An error occurred while fetching data. Please try again."})}});g.addEventListener("click",async function(){c.style.display="block";try{const r=await u(h.value.trim(),a);f(r.hits,!1),r.hits.length===0?(l(),b()):a++}catch(r){c.style.display="none",console.error("Error fetching more data:",r),iziToast.error({title:"Error",message:"An error occurred while fetching more data. Please try again."})}});g.addEventListener;
//# sourceMappingURL=commonHelpers.js.map
